# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cardreader', '0002_auto_20160421_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 4, 24, 19, 53, 35, 471538, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
