# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardreader', '0003_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='w_num',
            field=models.CharField(max_length=8),
        ),
    ]
